# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='game',
            name='home_team',
        ),
        migrations.RemoveField(
            model_name='game',
            name='round',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='game',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='round',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='team',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='user',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Round',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='Tip',
        ),
    ]
