# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('O', 'Ongoing'), ('C', 'Completed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='round',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('O', 'Ongoing'), ('C', 'Completed')], max_length=10),
        ),
    ]
