# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160209_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='fox_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
