# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160209_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='fox_id',
            field=models.IntegerField(unique=True),
        ),
    ]
