# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_team_fox_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='fox_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
