# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20160209_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Team'),
        ),
    ]
