# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20160210_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='home_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
