# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_roundscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='fox_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
