# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20160306_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='difference',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
