# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20160302_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='fox_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
