# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20160302_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='id',
        ),
        migrations.AlterField(
            model_name='team',
            name='fox_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
