# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-06 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_round_reminders_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='stadium',
            field=models.CharField(max_length=50),
        ),
    ]
